KOLOR_TLO = "#F4F6FB"
KOLOR_SIDEBAR = "#1B2340"
KOLOR_SIDEBAR_TEKST = "#E8EAF3"
KOLOR_AKCENT = "#3D5AFE"
KOLOR_AKCENT_HOVER = "#5470FF"
KOLOR_KARTA = "#FFFFFF"
KOLOR_OBRAMOWANIE = "#E1E4EC"
KOLOR_TEKST_GLOWNY = "#1C2333"
KOLOR_TEKST_DRUGORZEDNY = "#6B7280"
KOLOR_WIERSZ_PARZYSTY = "#FFFFFF"
KOLOR_WIERSZ_NIEPARZYSTY = "#F7F8FC"
KOLOR_WIERSZ_ZAZNACZONY = "#E8ECFF"
KOLOR_NAGLOWEK_TABELI = "#EEF0F7"
KOLOR_BLAD = "#DC2626"

SZEROKOSC_SIDEBAR = 220
ODSTEP_MALY = 8
ODSTEP_SREDNI = 16
ODSTEP_DUZY = 24
PROMIEN_NAROZNIKA = 8

# Krotki (nazwa, rozmiar, waga), NIE ctk.CTkFont(...) - CTkFont wymaga juz istniejacego
# roota Tk, a ten modul jest importowany zanim ctk.CTk() powstanie.
NAGLOWEK_1 = ("Segoe UI", 22, "bold")
NAGLOWEK_2 = ("Segoe UI", 16, "bold")
CZCIONKA_ETYKIETA = ("Segoe UI", 13)
CZCIONKA_TRESC = ("Segoe UI", 13)
CZCIONKA_TRESC_POGRUBIONA = ("Segoe UI", 13, "bold")
CZCIONKA_DROBNA = ("Segoe UI", 11)
