"""faktury_faza10_inwentaryzacja

Revision ID: 16304fc92992
Revises: 3e246719bd70
Create Date: 2026-07-13 20:29:11.507783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '16304fc92992'
down_revision: Union[str, Sequence[str], None] = '3e246719bd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liczniki_numeracji_inwentaryzacji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('ostatni_numer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rok', name='uq_liczniki_numeracji_inwentaryzacji_rok')
    )
    op.create_table('inwentaryzacje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazyn_id', sa.Integer(), nullable=False),
    sa.Column('numer', sa.String(length=100), nullable=False),
    sa.Column('data_rozpoczecia', sa.Date(), nullable=False),
    sa.Column('data_zakonczenia', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('W_TRAKCIE', 'ZAKONCZONA', name='status_inwentaryzacji'), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['magazyn_id'], ['magazyny.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inwentaryzacje_numer'), 'inwentaryzacje', ['numer'], unique=False)
    op.create_table('pozycje_inwentaryzacji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inwentaryzacja_id', sa.Integer(), nullable=False),
    sa.Column('produkt_id', sa.Integer(), nullable=False),
    sa.Column('stan_systemowy', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stan_faktyczny', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['inwentaryzacja_id'], ['inwentaryzacje.id'], ),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inwentaryzacja_id', 'produkt_id', name='uq_pozycje_inwentaryzacji_inwentaryzacja_produkt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pozycje_inwentaryzacji')
    op.drop_index(op.f('ix_inwentaryzacje_numer'), table_name='inwentaryzacje')
    op.drop_table('inwentaryzacje')
    op.drop_table('liczniki_numeracji_inwentaryzacji')
    # ### end Alembic commands ###
    # Autogenerate nie usuwa wlasnego typu ENUM przy drop_table (patrz Faza 7/8) -
    # status_inwentaryzacji jest tworzony tylko przez ta migracje, trzeba go zdjac recznie.
    postgresql.ENUM(name='status_inwentaryzacji').drop(op.get_bind(), checkfirst=True)
