"""faktury_faza3_dokument_powiazany_i_przyczyna_korekty

Revision ID: 36b76a08c45b
Revises: 7f5077e8eee3
Create Date: 2026-07-12 18:22:56.236269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b76a08c45b'
down_revision: Union[str, Sequence[str], None] = '7f5077e8eee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faktury', sa.Column('dokument_powiazany_id', sa.Integer(), nullable=True))
    op.add_column('faktury', sa.Column('przyczyna_korekty', sa.Text(), nullable=True))
    op.create_foreign_key('fk_faktury_dokument_powiazany_id_faktury', 'faktury', 'faktury', ['dokument_powiazany_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_faktury_dokument_powiazany_id_faktury', 'faktury', type_='foreignkey')
    op.drop_column('faktury', 'przyczyna_korekty')
    op.drop_column('faktury', 'dokument_powiazany_id')
    # ### end Alembic commands ###
