"""faktury_faza8_logika_stanow_magazynowych

Revision ID: 3e246719bd70
Revises: b9f788273497
Create Date: 2026-07-13 18:13:06.963865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3e246719bd70'
down_revision: Union[str, Sequence[str], None] = 'b9f788273497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liczniki_numeracji_magazynowej',
    sa.Column('id', sa.Integer(), nullable=False),
    # create_type=False: typ_dokumentu_magazynowego juz istnieje (utworzony w
    # migracji Fazy 7 dla dokumenty_magazynowe.typ), nie tworzymy go ponownie.
    sa.Column('typ', postgresql.ENUM('PZ', 'WZ', 'PW', 'RW', 'MM', name='typ_dokumentu_magazynowego', create_type=False), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('ostatni_numer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('typ', 'rok', name='uq_liczniki_numeracji_magazynowej_typ_rok')
    )
    # ADD COLUMN (w odroznieniu od CREATE TABLE) nie tworzy automatycznie typu
    # enum uzytego w kolumnie - trzeba go utworzyc jawnie przed ALTER TABLE.
    postgresql.ENUM('BLOKUJ', 'OSTRZEGAJ', name='tryb_blokady_stanu').create(
        op.get_bind(), checkfirst=True
    )
    # server_default do backfillu istniejacych wierszy firmy (kolumna NOT NULL na
    # tabeli, ktora moze juz miec dane) - usuwany zaraz po, docelowo wartosc
    # domyslna zyje tylko po stronie modelu (Python-level default), jak przy
    # pozostalych kolumnach enum w tej tabeli (np. domyslna_stawka_vat).
    op.add_column('firmy', sa.Column('tryb_blokady_ujemnego_stanu', postgresql.ENUM('BLOKUJ', 'OSTRZEGAJ', name='tryb_blokady_stanu', create_type=False), nullable=False, server_default='OSTRZEGAJ'))
    op.alter_column('firmy', 'tryb_blokady_ujemnego_stanu', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmy', 'tryb_blokady_ujemnego_stanu')
    op.drop_table('liczniki_numeracji_magazynowej')
    # ### end Alembic commands ###
    # Typ tryb_blokady_stanu jest tworzony wylacznie przez ta migracje (w
    # odroznieniu od wspoldzielonego typ_dokumentu_magazynowego) - trzeba go
    # zdjac recznie, autogenerate drop_column tego nie robi (patrz Faza 7).
    postgresql.ENUM(name='tryb_blokady_stanu').drop(op.get_bind(), checkfirst=True)
