"""faktury_faza2_aktywny_klient_i_licznik_numeracji

Revision ID: 7f5077e8eee3
Revises: 8a855a7184e2
Create Date: 2026-07-12 17:32:50.362699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5077e8eee3'
down_revision: Union[str, Sequence[str], None] = '8a855a7184e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liczniki_numeracji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('ostatni_numer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rok', name='uq_liczniki_numeracji_rok')
    )
    op.add_column(
        'klienci',
        sa.Column('aktywny', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('klienci', 'aktywny')
    op.drop_table('liczniki_numeracji')
    # ### end Alembic commands ###
