"""faktury_faza1_fundament

Revision ID: 8a855a7184e2
Revises: 
Create Date: 2026-07-12 17:15:25.618602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a855a7184e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('nip', sa.String(length=10), nullable=False),
    sa.Column('ulica', sa.String(length=255), nullable=True),
    sa.Column('kod_pocztowy', sa.String(length=10), nullable=True),
    sa.Column('miejscowosc', sa.String(length=255), nullable=True),
    sa.Column('kraj', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('bank_nazwa', sa.String(length=255), nullable=True),
    sa.Column('bank_numer_konta', sa.String(length=34), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('domyslna_stawka_vat', sa.Enum('STAWKA_23', 'STAWKA_8', 'STAWKA_5', 'STAWKA_0', 'ZW', name='stawka_vat'), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('klienci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('nip', sa.String(length=10), nullable=True),
    sa.Column('ulica', sa.String(length=255), nullable=True),
    sa.Column('kod_pocztowy', sa.String(length=10), nullable=True),
    sa.Column('miejscowosc', sa.String(length=255), nullable=True),
    sa.Column('kraj', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('domyslna_waluta', sa.String(length=3), nullable=False),
    sa.Column('domyslny_termin_platnosci_dni', sa.Integer(), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firmy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numer', sa.String(length=100), nullable=False),
    sa.Column('typ_dokumentu', sa.Enum('FAKTURA_VAT', 'PROFORMA', 'FAKTURA_ZALICZKOWA', 'FAKTURA_KONCOWA', 'FAKTURA_KORYGUJACA', 'NOTA_KORYGUJACA', 'RACHUNEK', name='typ_dokumentu'), nullable=False),
    sa.Column('klient_id', sa.Integer(), nullable=False),
    sa.Column('data_wystawienia', sa.Date(), nullable=False),
    sa.Column('data_sprzedazy', sa.Date(), nullable=False),
    sa.Column('termin_platnosci', sa.Date(), nullable=False),
    sa.Column('waluta', sa.String(length=3), nullable=False),
    sa.Column('kurs_waluty', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.Enum('ROBOCZA', 'WYSTAWIONA', 'WYSLANA', 'OPLACONA_CZESCIOWO', 'OPLACONA', 'PO_TERMINIE', 'ANULOWANA', name='status_faktury'), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['klient_id'], ['klienci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faktury_numer'), 'faktury', ['numer'], unique=False)
    op.create_table('pozycje_faktury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=500), nullable=False),
    sa.Column('ilosc', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('jednostka_miary', sa.String(length=20), nullable=False),
    sa.Column('cena_netto_grosze', sa.BigInteger(), nullable=False),
    sa.Column('stawka_vat', sa.Enum('STAWKA_23', 'STAWKA_8', 'STAWKA_5', 'STAWKA_0', 'ZW', name='stawka_vat'), nullable=False),
    sa.Column('wartosc_netto_grosze', sa.BigInteger(), nullable=False),
    sa.Column('wartosc_vat_grosze', sa.BigInteger(), nullable=False),
    sa.Column('wartosc_brutto_grosze', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktury.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pozycje_faktury')
    op.drop_index(op.f('ix_faktury_numer'), table_name='faktury')
    op.drop_table('faktury')
    op.drop_table('klienci')
    op.drop_table('firmy')
    # ### end Alembic commands ###
