"""faktury_faza5_platnosci

Revision ID: ad07fd9fe966
Revises: 36b76a08c45b
Create Date: 2026-07-13 12:35:18.556590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad07fd9fe966'
down_revision: Union[str, Sequence[str], None] = '36b76a08c45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platnosci_faktury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.Column('data_platnosci', sa.Date(), nullable=False),
    sa.Column('kwota_grosze', sa.BigInteger(), nullable=False),
    sa.Column('notatka', sa.String(length=500), nullable=True),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktury.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platnosci_faktury_faktura_id'), 'platnosci_faktury', ['faktura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platnosci_faktury_faktura_id'), table_name='platnosci_faktury')
    op.drop_table('platnosci_faktury')
    # ### end Alembic commands ###
