"""faktury_faza7_modele_magazynowe

Revision ID: b9f788273497
Revises: ad07fd9fe966
Create Date: 2026-07-13 17:48:35.674441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b9f788273497'
down_revision: Union[str, Sequence[str], None] = 'ad07fd9fe966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazyny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('lokalizacja', sa.String(length=500), nullable=True),
    sa.Column('aktywny', sa.Boolean(), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firmy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produkty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('jednostka_miary', sa.String(length=20), nullable=False),
    sa.Column('cena_netto_grosze', sa.BigInteger(), nullable=False),
    sa.Column('domyslna_stawka_vat', postgresql.ENUM('STAWKA_23', 'STAWKA_8', 'STAWKA_5', 'STAWKA_0', 'ZW', name='stawka_vat', create_type=False), nullable=False),
    sa.Column('jest_magazynowy', sa.Boolean(), nullable=False),
    sa.Column('aktywny', sa.Boolean(), nullable=False),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firmy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stany_magazynowe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produkt_id', sa.Integer(), nullable=False),
    sa.Column('magazyn_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stan_minimalny', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['magazyn_id'], ['magazyny.id'], ),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produkt_id', 'magazyn_id', name='uq_stany_magazynowe_produkt_magazyn')
    )
    op.create_table('dokumenty_magazynowe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.Enum('PZ', 'WZ', 'PW', 'RW', 'MM', name='typ_dokumentu_magazynowego'), nullable=False),
    sa.Column('numer', sa.String(length=100), nullable=False),
    sa.Column('data_dokumentu', sa.Date(), nullable=False),
    sa.Column('magazyn_zrodlowy_id', sa.Integer(), nullable=True),
    sa.Column('magazyn_docelowy_id', sa.Integer(), nullable=True),
    sa.Column('faktura_powiazana_id', sa.Integer(), nullable=True),
    sa.Column('utworzono', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('zaktualizowano', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faktura_powiazana_id'], ['faktury.id'], ),
    sa.ForeignKeyConstraint(['magazyn_docelowy_id'], ['magazyny.id'], ),
    sa.ForeignKeyConstraint(['magazyn_zrodlowy_id'], ['magazyny.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dokumenty_magazynowe_numer'), 'dokumenty_magazynowe', ['numer'], unique=False)
    op.create_table('pozycje_dokumentow_magazynowych',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dokument_id', sa.Integer(), nullable=False),
    sa.Column('produkt_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notatka', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dokument_id'], ['dokumenty_magazynowe.id'], ),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pozycje_dokumentow_magazynowych')
    op.drop_index(op.f('ix_dokumenty_magazynowe_numer'), table_name='dokumenty_magazynowe')
    op.drop_table('dokumenty_magazynowe')
    op.drop_table('stany_magazynowe')
    op.drop_table('produkty')
    op.drop_table('magazyny')
    # ### end Alembic commands ###
    # Autogenerate nie usuwa wlasnych typow ENUM przy drop_table - typ_dokumentu_magazynowego
    # jest tworzony tylko przez ta migracje (w odroznieniu od wspoldzielonego stawka_vat,
    # ktory zyje od Fazy 1 i celowo nie jest tu ruszany), wiec trzeba go zdjac recznie.
    postgresql.ENUM(name='typ_dokumentu_magazynowego').drop(op.get_bind(), checkfirst=True)
